### PR TITLE
GL300M

### PR DESCRIPTION
**Pull request by DanBoothDev**
Addition of GL300M version 0701

### CODE REVIEW

**Review by ckrey — CHANGES_REQUESTED** [review]
Hi @DanBoothDev , thanks for the additional device type

There is a problem because you have GTNMR for "F50701" twice. I think you should have the new section for "GTLOC" only

And, please share the GL300*Interface*07.01.pdf protocol description with us as a direct message.

Bildschirmfoto 2020-03-05 um 09 33 35

**Comment by jpmens** [comment]
@DanBoothDev you can send me the requested interface description at `jp-ot@mens.de`, thank you.

**Comment by DanBoothDev** [comment]
Agreed @ckrey 
The interface doc has been sent @jpmens

**Comment by jpmens** [comment]
@DanBoothDev thank you, received and confirmed via email. Much appreciated.

**Comment by ckrey** [comment]
Thanks @DanBoothDev. Please keep in touch

**Pull request merged**
